name: ir-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - langchain
  - langgraph
  - openai
  - langchain-openai
  - langchain-groq
  - langchain-community
  - langchain-core
  - langchain-anthropic
  - python-dotenv
  - rank-bm25
  - huggingface_hub
  - datasets
  - faiss-cpu
  - pinecone
  - pip
  - pip:
    - ragas
    - llama-index-vector-stores-pinecone
    - llama-index-embeddings-openai